spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://jeevandhamala095:57XwK0CMhVKbfqEU@cluster0.rc0yl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
  mail:
    host: smtp.gmail.com
    port: 587
    username: gbuxssideas@gmail.com
    password: yzen pktz zuxr iini
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: redis-17115.c93.us-east-1-3.ec2.redns.redis-cloud.com
    port: 17115
    password: c0SDeH6GSZ5wtlBNWlnyE1AOpE0rROci



server:
  servlet:
    context-path: /journal/


WEATHER_API_KEY: eab80f77fb90390a0958ef376ba0934e


