spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://jeevandhamala095:57XwK0CMhVKbfqEU@cluster0.rc0yl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
  mail:
    host: smtp.gmail.com
    port: 587
    username: gbuxssideas@gmail.com
    password: yzen pktz zuxr iini
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: redis-17115.c93.us-east-1-3.ec2.redns.redis-cloud.com
    port: 17115
    password: c0SDeH6GSZ5wtlBNWlnyE1AOpE0rROci



server:
  servlet:
    context-path: /journal/


  kafka:
    bootstrap-servers: aws.confluent.cloud:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: weekly-sentiment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: net.engineeringdigest.journalApp.model
    properties:
      security:
        protocol: SASL_SSL
      sasl:
        mechanism: PLAIN
        jaas:
          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='xxxxx' password='xxxxxxxxxxxxxx';
      session:
        timeout:
          ms: 45000



WEATHER_API_KEY: eab80f77fb90390a0958ef376ba0934e
SECRET_KEY: Ts2AShXD8e5DY4xCidYmVi8zmSuXNo3s
  



